//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HajjBot
{
    using System;
    using System.Collections.Generic;

    public partial class ConversationStarter
    {
        public decimal id { get; set; }
        public string fromId { get; set; }
        public string fromName { get; set; }
        public string toId { get; set; }
        public string toName { get; set; }
        public string serviceUrl { get; set; }
        public string channelId { get; set; }
        public string conversationId { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    }
}
